net/urls.py
from django.urls import include, re_path
from astrometry.net import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = []

from astrometry.net.views.home import home, support, api_help, explore

urlpatterns.extend([
    re_path(r'^/?$', home),
    re_path(r'^support/?$', support, name='support'),
    re_path(r'^api_help/?$', api_help, name='api-help'),
    # re_path(r'^new_api_key/?$', 'new_api_key', name='new_api_key'),
    re_path(r'^explore/?$', explore, name='explore'),
])

if settings.ENABLE_SOCIAL:
    urlpatterns.append(
        re_path('', include('social.apps.django_app.urls', namespace='social'))
    )

if settings.ENABLE_SOCIAL2:
    urlpatterns.append(
        re_path('', include('social_django.urls', namespace='social'))
    )

from astrometry.net.views.home import signin, signout, signedin, newuser
urlpatterns.extend([
    re_path(r'^signin/?',   signin, name='signin'),
    re_path(r'^signout/?',  signout, name='signout'),
    re_path(r'^signedin/?', signedin),
    re_path(r'^newuser/?',  newuser),
])

from astrometry.net.views.search import images, users
urlpatterns.extend([
    re_path(r'^search/images/?$', images),
    re_path(r'^search/users/?$',  users),
])

jobpattern = r'[0-9-]+'
subpattern = r'[0-9-]+'
imagepattern = r'[0-9-]+'
idpattern = r'[0-9-]+'
tagpattern = r'[\s|\S]+'

from astrometry.net.views.submission import upload_file, status, job_log_file, job_log_file2, index
urlpatterns.extend([
    re_path(r'^upload/?$', upload_file, name='upload-file'),
    re_path(r'^status/(?P<subid>' + subpattern + r')/?', status,
        name='submission_status'),
    re_path(r'^joblog/(?P<jobid>' + jobpattern + r')/?', job_log_file,
        name='job_log_file'),
    re_path(r'^joblog2/(?P<jobid>' + jobpattern + r')/?', job_log_file2,
        name='job_log_file_2'),
    re_path(r'^submissions/(?P<user_id>' + idpattern + r')/?$', index),
])

from astrometry.net.views.user import (
    index, dashboard, user_profile, dashboard_submissions, dashboard_user_images, dashboard_albums,
    dashboard_create_album, dashboard_profile, save_profile, user_images, user_albums,
    user_submissions, user_autocomplete)
urlpatterns.extend([
    re_path(r'^dashboard/?$', dashboard, name='dashboard'),
    #(r'^dashboard/apikey/?$', 'get_api_key'),  # made redundant by inclusion of api key in dashboard profile
    re_path(r'^dashboard/submissions/?$', dashboard_submissions, name='dashboard_submissions'),
    re_path(r'^dashboard/images/?$', dashboard_user_images, name='dashboard_user_images'),
    re_path(r'^dashboard/albums/?$', dashboard_albums, name='dashboard_albums'),
    re_path(r'^dashboard/create_album/?$', dashboard_create_album, name='dashboard_create_album'),
    re_path(r'^dashboard/profile/?$', dashboard_profile, name='dashboard_profile'),
    re_path(r'^dashboard/profile/save/?$', save_profile, name='save_profile'),
    re_path(r'^users/?$', index, name='users'),
    re_path(r'^users/(?P<user_id>' + idpattern + r')/?$', user_profile, name='user_profile'),
    re_path(r'^users/(?P<user_id>' + idpattern + r')/images/?$', user_images, name='user_images'),
    re_path(r'^users/(?P<user_id>' + idpattern + r')/albums/?$', user_albums, name='user_albums'),
    re_path(r'^users/(?P<user_id>' + idpattern + r')/submissions/?$', user_submissions, name='user_submissions'),
    re_path(r'^users/autocomplete/?$', user_autocomplete, name='user_autocomplete'),
])

from astrometry.net.views.image import (
    index, index_tag, annotated_image, grid_image, index_location, index_nearby, index_recent, index_all, index_by_user,
    index_user, index_album, hide, unhide, user_image, edit, search, serve_image, serve_thumbnail_image, image_set,
    onthesky_image, sdss_image, galex_image, unwise_image, legacysurvey_image, red_green_image, extraction_image, wcs_file, new_fits_file,
    kml_file, rdls_file, axy_file, corr_file)
urlpatterns.extend([
    re_path(r'^annotated_(?P<size>full|display)/(?P<jobid>' + jobpattern + r')/?', annotated_image, name='annotated_image'),
    re_path(r'^grid_(?P<size>full|display)/(?P<jobid>' + jobpattern + r')/?', grid_image, name='grid_image'),
    re_path(r'^user_images/?$', index, name='images'),
    re_path(r'^user_images/tag/?$', index_tag, name='images-tag'),
    re_path(r'^user_images/location/?$', index_location, name='images-location'),
    re_path(r'^user_images/nearby/(?P<user_image_id>' + idpattern + r')/?$', index_nearby, name='images-nearby'),
    re_path(r'^user_images/recent/?$', index_recent),
    re_path(r'^user_images/all/?$', index_all),
    re_path(r'^user_images/by_user/?$', index_by_user),
    re_path(r'^user_images/user/(?P<user_id>' + idpattern + r')/?$', index_user),
    re_path(r'^user_images/album/(?P<album_id>' + idpattern + r')/?$', index_album),
    re_path(r'^user_images/(?P<user_image_id>' + idpattern + r')/hide/?$', hide),
    re_path(r'^user_images/(?P<user_image_id>' + idpattern + r')/unhide/?$', unhide),
    re_path(r'^user_images/(?P<user_image_id>' + idpattern + r')/?$', user_image, name='user_image'),
    re_path(r'^user_images/(?P<user_image_id>' + idpattern + r')/edit/?$', edit, name='image_edit'),
    re_path(r'^user_images/search/?$', search, name='image-search'),
    re_path(r'^image/(?P<id>' + imagepattern + r')/?$', serve_image, name='serve_image'),
    re_path(r'^thumbnail_of_image/(?P<id>' + imagepattern + r')/?$', serve_thumbnail_image, name='serve_thumbnail_image'),
    re_path(r'^images/(?P<category>\w+)/(?P<id>' + idpattern + r')/?$', image_set),
    re_path(r'^sky_plot/zoom(?P<zoom>[0-3])/(?P<calid>' + idpattern + r')/?$', onthesky_image, name='onthesky_image'),
    re_path(r'^sdss_image_(?P<size>full|display)/(?P<calid>' + idpattern + r')/?$', sdss_image, name='sdss_image'),
    re_path(r'^galex_image_(?P<size>full|display)/(?P<calid>' + idpattern + r')/?$', galex_image, name='galex_image'),
    re_path(r'^unwise_image_(?P<size>full|display)/(?P<calid>' + idpattern + r')/?$', unwise_image, name='unwise_image'),
    re_path(r'^legacysurvey_image_(?P<size>full|display)/(?P<calid>' + idpattern + r')/?$', legacysurvey_image, name='legacysurvey_image'),
    re_path(r'^red_green_image_(?P<size>full|display)/(?P<job_id>' + idpattern + r')/?$', red_green_image, name='red_green_image'),
    re_path(r'^extraction_image_(?P<size>full|display)/(?P<job_id>' + idpattern + r')/?$', extraction_image, name='extraction_image'),
    re_path(r'^wcs_file/(?P<jobid>' + idpattern + r')/?$', wcs_file, name='wcs-file'),
    re_path(r'^new_fits_file/(?P<jobid>' + idpattern + r')/?$', new_fits_file, name='new-fits-file'),
    re_path(r'^kml_file/(?P<jobid>' + idpattern + r')/?$', kml_file, name='kml-file'),
    re_path(r'^rdls_file/(?P<jobid>' + idpattern + r')/?$', rdls_file, name='rdls-file'),
    re_path(r'^axy_file/(?P<jobid>' + idpattern + r')/?$', axy_file, name='axy-file'),
    re_path(r'^corr_file/(?P<jobid>' + idpattern + r')/?$', corr_file, name='corr-file'),
])
#     
#     urlpatterns += patterns('astrometry.net.views.enhance',
#         (r'^enhance_ui/(?P<user_image_id>' + idpattern + r')/?$', 'enhanced_ui'),
#         url(r'^enhanced_image_(?P<size>full|display)/(?P<job_id>' + idpattern + r')/?$', 'enhanced_image', name='enhanced_image'),
#     )
#     

from astrometry.net.views.album import album, delete as album_delete, edit, new as album_new
urlpatterns.extend([
    re_path(r'^albums/(?P<album_id>' + idpattern + r')/?$', album, name='album'),
    re_path(r'^albums/(?P<album_id>' + idpattern + r')/delete/?$', album_delete, name='album_delete'),
    re_path(r'^albums/(?P<album_id>' + idpattern + r')/edit/?$', edit, name='album_edit'),
    re_path(r'^albums/new/?$', album_new, name='album_new'),
])

from astrometry.net.views.tag import index, delete, new, tag_autocomplete
urlpatterns.extend([
    re_path(r'^tags/?$', index, name='tags'),
    re_path(r'^(?P<category>\w+)/(?P<recipient_id>' + idpattern + r')/tags/(?P<tag_id>' + tagpattern + r')/delete/?$', delete, name='tag_delete'),
    re_path(r'^(?P<category>\w+)/(?P<recipient_id>' + idpattern + r')/tags/new/?$', new, name='tag_new'),
    re_path(r'^tags/autocomplete/?$', tag_autocomplete, name='tag_autocomplete'),
])

from astrometry.net.views.flag import update_flags
urlpatterns.append(
    re_path(r'^(?P<category>\w+)/(?P<recipient_id>' + idpattern + r')/flags/update/?$', update_flags, name='update_flags'),
)

from astrometry.net.views.comment import new as new_comment, delete as delete_comment
urlpatterns.extend([
    re_path(r'^(?P<category>\w+)/(?P<recipient_id>' + idpattern + r')/comments/new/?$', new_comment, name='comment_new'),
    re_path(r'^comments/(?P<comment_id>' + idpattern + r')/delete/?$', delete_comment, name='comment_delete'),
])

from astrometry.net.views.license import edit
urlpatterns.append(
    re_path(r'^(?P<licensable_type>\w+)/(?P<licensable_id>' + idpattern + r')/license/edit/?$', edit, name='edit_license')
)


#     psidpattern = r'[0-9-]+'
#     
#     urlpatterns += patterns('astrometry.net.views.admin',
#                             (r'^admin/procsub/(?P<psid>'+psidpattern + r')?$', 'procsub'),
#                             (r'^admin/?', 'index'),
#                             )

from astrometry.net.api import (
    api_login, api_upload, url_upload, api_sdss_image_for_wcs, api_galex_image_for_wcs,
    api_submission_images, submission_status, myjobs, job_status, calibration, tags,
    machine_tags, objects_in_field, annotations_in_field, job_info, jobs_by_tag)

urlpatterns.extend([
    re_path(r'^api/login/?$', api_login, name='api_login'),
    re_path(r'^api/upload/?$', api_upload, name='api_upload'),
    re_path(r'^api/url_upload/?$', url_upload, name='api_url_upload'),
    re_path(r'^api/sdss_image_for_wcs/?$', api_sdss_image_for_wcs, name='api_sdss_image_for_wcs'),
    re_path(r'^api/galex_image_for_wcs/?$', api_galex_image_for_wcs, name='api_galex_image_for_wcs'),

net/views/search.py
from django.shortcuts import get_object_or_404, redirect, render
from django.template import Context, RequestContext
from django import forms
from django.db.models import Count

try:
    # py3
    from urllib.parse import urlencode
except ImportError:
    # py2
    from urllib import urlencode

from astrometry.net.models import *
from astrometry.net.util import get_page, get_session_form


class ImageSearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off'}),
                                                  required=False)

def images(req):
    images = UserImage.objects.all_visible()
    form = ImageSearchForm(req.GET)
    if form.is_valid():
        query_string = urlencode(form.cleaned_data)
        query = form.cleaned_data.get('query')
        if query:
            images = images.filter(tags__text__icontains=query)

    images = images.order_by('submission__submitted_on').distinct()
    page_number = req.GET.get('page',1)
    image_page = get_page(images,3*10,page_number)
    context = {
        'image_search_form': form,
        'image_page': image_page,
        'query_string': query_string,
    }
    return render(req, 'search/user_images.html', context)

class UserSearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off'}),
                                                  required=False)

def users(req):
    users = User.objects.all()
    form = UserSearchForm(req.GET)
    if form.is_valid():
        query_string = urlencode(form.cleaned_data)
        query = form.cleaned_data.get('query')
        if query:
            users = users.filter(profile__display_name__icontains=query)

    sort = req.GET.get('sort', 'name')
    order = 'profile__display_name'
    if sort == 'name':
        #profiles = (UserProfilek.extra(select={'lower_name':'lower(profile.display_name)'})
        #             .order_by('lower_name'))
        order = 'profile__display_name'
    elif sort == 'date':
        order = 'date_joined'
    elif sort == 'images':
        users = users.annotate(Count('user_images'))
        order = '-user_images__count'
    
    users = users.order_by(order)
    #users = users.order_by(order)
    page_number = req.GET.get('page',1)
    user_page = get_page(users,20,page_number)
    context = {
        'user_search_form': form,
        'user_page': user_page,
        'query_string': query_string,
    }
    return render(req, 'search/users.html', context)

net/views/tag.py
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest, QueryDict
from django.shortcuts import render, get_object_or_404, redirect
from django.template import Context, RequestContext, loader
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.template.loader import render_to_string
from django.db.models import Count

from astrometry.net.models import *
from astrometry.net import settings
from astrometry.net.util import get_page, store_session_form
from astrometry.net.log import *
from django import forms
from django.http import HttpResponseRedirect
import json

class TagForm(forms.ModelForm):
    # so the primary key restriction isn't enforced
    text = forms.CharField(widget=forms.TextInput(attrs={'size':'30'}),
                           max_length=4096)
    class Meta:
        model = Tag
        exclude = ('text',)

@login_required
def delete(req, category=None, recipient_id=None, tag_id=None):
    if category == 'user_image':
        tag = get_object_or_404(TaggedUserImage, user_image=recipient_id, tag=tag_id)
        if tag.tagger == req.user or tag.user_image.user == req.user:
            tag.delete()
    else:
        # TODO - do something useful?
        pass

    redirect_url = req.GET.get('next', '/')
    J = {'success': True}
    if req.is_ajax():
        response = json.dumps(J)
        return HttpResponse(response, content_type='application/javascript')
    else:
        return HttpResponseRedirect(redirect_url)

@login_required
def new(req, category=None, recipient_id=None):
    if req.method == 'POST':
        recipient = None
        recipient_owner = None
        if category == 'user_image':
            recipient = get_object_or_404(UserImage, pk=recipient_id)
            recipient_owner = recipient.user
        form = TagForm(req.POST)
        redirect_url = req.POST.get('next','/')
        J = {}
        if form.is_valid():
            tag,created = Tag.objects.get_or_create(**form.cleaned_data)
            if category == 'user_image':
                tagged_user_image,created = TaggedUserImage.objects.get_or_create(
                    user_image=recipient,
                    tag=tag,
                    tagger=req.user
                )
            
            if req.is_ajax():
                form = TagForm()
                context = {
                    'tag': tag,
                    'category': category,
                    'recipient_id': recipient_id,
                    'recipient_owner': recipient_owner,
                    'next': redirect_url,
                }
                tag_html = render_to_string('tag/tag.html', context, req)

                J['success'] = created
                J['tag_html'] = tag_html
        else:
            if req.is_ajax():
                J['success'] = False
            else:
                store_session_form(req.session, TagForm, req.POST)

        if req.is_ajax():
            context = {
                'tag_form': form,
                'category': category,
                'recipient_id': recipient_id,
                'recipient_owner': recipient_owner,
                'next': redirect_url,
            }
            form_html = render_to_string('tag/form.html', context, req)
            J['form_html'] = form_html
            
            response = json.dumps(J)
            return HttpResponse(response, content_type='application/javascript')
        else:
            return redirect(redirect_url)

class TagSearchForm(forms.Form):
    query = forms.CharField(widget=forms.TextInput(attrs={'autocomplete':'off'}),
                                                  required=False)
    exact = forms.BooleanField(initial=False, required=False)

def index(req, tags=Tag.objects.all(), 
          template_name='tag/index.html', context={}):

    logmsg('tags:', tags.count())

    form = TagSearchForm(req.GET)
    if form.is_valid():
        query = form.cleaned_data.get('query')
        if query:
            tags = tags.filter(text__icontains=query)
            logmsg('query for "%s":' % query, tags.count())
        else:
            logmsg('no query')

    tags = tags.annotate(Count('user_images'))
    sort = req.GET.get('sort', 'freq')
    order = '-user_images__count'
    if sort == 'name':
        order = 'text'
    elif sort == 'freq':
        tags = tags.annotate(Count('user_images'))
        order = '-user_images__count'
    
    tags = tags.order_by(order)
    logmsg('tags:', tags.count())
    page_number = req.GET.get('page', 1)
    page = get_page(tags, 50, page_number)
    context.update({
        'tag_page': page,
        'tags': tags,
        'tag_search_form': form,
    })
    return render(req, template_name, context)

def tag_autocomplete(req):
    name = req.GET.get('q','')
    tags = Tag.objects.filter(text__icontains=name)[:8]
    response = HttpResponse(''.join([t.text+'\n' for t in tags]), content_type='text/plain')
    return response

net/templates/user_image/edit.html
{% extends "user_image/view.html" %}

{% block inline_css %}
{% endblock %}

{% block javascript %}
{% endblock %}

{% block title %}
{{block.super}} &gt;
<a href="{% url 'image_edit' user_image_id=image.id %}">Edit</a>
{% endblock %}

{% block content %}
<form method="post" action="{% url 'image_edit' user_image_id=image.id %}">
{% csrf_token %}
<table class="settings_table">
<tr>
    <td class="leftcolumn" style="border:0px">
        <div class="setting_title">Description:</div>
        <div class="setting_description">
        </div>
    </td>
    <td style="border:0px">
        {{ image_form.description }}
        {{ image_form.description.errors }}
    </td>
</tr>
<tr>
    <td class="leftcolumn">
        <div class="setting_title">Album</div>
        <div class="setting_description">
            Select an album to move this image into. You can
            <a href="{% url 'dashboard_create_album' %}">
            create new albums</a> at your dashboard.
        </div>
    </td>
    <td>
        {{ image_form.album }}
    </td>
</tr>
<tr>
    <td class="leftcolumn">
        <div class="setting_title">Flags</div>
        <div class="setting_description"></div>
    </td>
    <td>
        {% include 'flag/chooser.html' with flags=flags selected_flags=selected_flags %}
    </td>
</tr>
<tr>
    <td class="leftcolumn">
        <div class="setting_title">Visibility:</div>
        <div class="setting_description">
            Permit anyone to view this image?
        </div>
    </td>
    <td>
        {{ image_form.publicly_visible }}
        {{ image_form.publicly_visible.errors }}
    </td>
</tr>
<tr>
    <td class="leftcolumn">
        <div class="setting_title">License:</div>
        <div class="setting_description">
            Your default license setting is
            {% include 'license/license_link.html' with license=user.get_profile.default_license %}.
        </div>
    </td>
    <td>
        <b>Allow commercial use?</b><br />
        {{ license_form.allow_commercial_use }}
        {{ license_form.allow_commercial_use.errors }}
        <br /><br />
        <b>Allow modifications?</b><br />
        {{ license_form.allow_modifications.errors }}
        {{ license_form.allow_modifications }}
    </td>
</tr>
</table>
<br />
<div style="text-align:center">
    <input type="submit" value="Save Changes" class="bigbutton" />
    <a href="{{ image.get_absolute_url }}" style="margin-left:10px">Cancel</a>
</div>
</form>
{% endblock %}

net/templates/user_image/image_set.html
<div class="image_set">
{% spaceless %}
{% for uimage in images %}
    <div class="thumbnail_container
    {% if thumbnail_size == 'small' %}
        thumbnail_small
    {% else %}
    {% if thumbnail_size == 'medium' %}
        thumbnail_medium
    {% else %}
        thumbnail_large
    {% endif %}{% endif %}
    ">
        <a href="{% url 'user_image' uimage.id %}">
            {% with offset_x=uimage.image.get_offset_x_of_thumbnail offset_y=uimage.image.get_offset_y_of_thumbnail thumb_width=uimage.image.get_thumbnail_width %}
            <img class="image"
		 {% if multi_hosts %}
		 src="http://{{ multi_hosts.get }}{% url 'serve_thumbnail_image' id=uimage.image.id %}"
		 {% else %}
		 src="{% url 'serve_thumbnail_image' id=uimage.image.id %}"
		 {% endif %}
                 {% if thumbnail_size == 'small' %}
                 style="left: {% widthratio offset_x 235 100 %}px;
                        top: {% widthratio offset_y 235 100 %}px;
                        width: {% widthratio thumb_width 235 100 %}px;
                        height: auto;"
                 {% else %}
                 {% if thumbnail_size == 'medium' %}
                 style="left: {% widthratio offset_x 235 170 %}px;
                        top: {% widthratio offset_y 235 170 %}px;
                        width: {% widthratio thumb_width 235 170 %}px;
                        height: auto;"
                 {% else %}
                 style="left: {{ offset_x }}px;
                        top: {{ offset_y }}px;"
                 {% endif %}{% endif %}
             />
            {% endwith %}
        </a>
    </div>
{% empty %}
    No images.
{% endfor %}
{% endspaceless %}
</div>

net/templates/user_image/index.html
{% extends 'base.html' %}
{% load custom_tags %}

{% block inline_css %}
{{block.super}}
{% include 'user_image/image_set.css' %}
{% include 'view_menu.css' %}
<style type="text/css">
#search_block {
    padding: 10px;
    background-color: #eee;
}
#search_menu {
    float: left;
}
#show_images_menu {
    float: right;
}
#search_settings {
    padding: 10px 10px 0px 10px;
    padding-left: 10px;
    
}
#search_menu ul.view_menu li {
    margin-bottom: 0px;
}
#image_settings {
    padding: 10px; 
}
#sort_menu {
    float: left;
}
#thumbnail_size_menu {
    float: right;
}
</style>
{% endblock %}

{% block title %}
<a href="{% url 'images' %}">Images</a>
{% endblock %}

{% block content %}
    <form method="get" action="">
    <input type="hidden" name="thumbnail_size" value="{{ request.GET.thumbnail_size }}" />
    <input type="hidden" name="sort" value="{{ request.GET.sort }}" />

    <div id="search_block">
        <div id="search_menu">
            {% block search_menu %}
            {% url 'images-tag' as tag_url %}
            {% url 'images-location' as location_url %}
            {% with curr_url=request.path %}
            Search:
            <a {% if curr_url == tag_url %}class="selected" {% endif %}href="{{ tag_url }}">tag</a> |
            <a {% if curr_url == location_url %}class="selected" {% endif %}href="{{ location_url }}">location</a>
            {% endwith %}
            {% endblock %}
        </div>
        <div id="show_images_menu">
            Show: 
            {{ show_images_form.calibrated }}<label for="id_calibrated">calibrated</label>&nbsp;&nbsp;
            {{ show_images_form.processing }}<label for="id_processing">processing</label>&nbsp;&nbsp;
            {{ show_images_form.failed }}<label for="id_failed">failed</label>&nbsp;&nbsp;
            </form>
        </div>
        <div style="clear:both"></div>
        <div id="search_settings">
            {% block search_settings %}
            {% endblock %}
        </div>
        </form>
    </div>
    <div id="search_results">
        {% block search_results %}
            <div id="image_settings">
                <div id="sort_menu">
                    Sort:
                    <a href="">date submitted</a>
                </div>
                <div id="thumbnail_size_menu">
                    {% with size=request.GET.thumbnail_size %}
                    View:
                    <a {% if size == 'small' %}class="selected" {% endif %}href="?{% query_string 'thumbnail_size' 'small' %}">small</a> | 
                    <a {% if size == 'medium' %}class="selected" {% endif %}href="?{% query_string 'thumbnail_size' 'medium' %}">medium</a> | 
                    <a {% if size == 'large' or not size %}class="selected" {% endif %}href="?{% query_string 'thumbnail_size' 'large' %}">large</a>
                    {% endwith %}
                </div>
                <div style="clear:both"></div>
            </div>
            {% include 'user_image/paginated_image_set.html' with image_page=image_page thumbnail_size=request.GET.thumbnail_size %}
        {% endblock %}
    </div>
    </form>
{% endblock %}

net/templates/user_image/index_all.html
{% extends 'user_image/index.html' %}

{% block title %}
{{block.super}} &gt; 
<a href="{% url 'index_all' %}">All</a>
{% endblock %}

{% block user_image_index_content %}
    {% include 'user_image/paginated_image_set.html' with image_page=image_page thumbnail_size=request.GET.thumbnail_size %}
{% endblock %}

net/templates/user_image/index_by_user.html
{% extends 'user_image/index.html' %}

{% block inline_css %}
{{block.super}}
<style type="text/css">
#images_by_user li {
    list-style: none;
    overflow:auto;
    width:100%;
}
</style>
{% endblock %}

{% block title %}
{{block.super}} &gt; 
<a href="{% url 'index_by_user' %}">By User</a>
{% endblock %}

{% block user_image_index_content %}
<ul id="images_by_user">
{% for user in users %}
    <li><h3>{% include 'user/display_name.html' with user=user %}</h3>
        <p>
            <a href="{% url 'index_user' user_id=user.id %}">
                {{user.user_images.all.count}} image{{ user.user_images.all.count|pluralize }}
            </a>
        </p>
    </li>
{% endfor %}
</ul>
{% endblock %}

net/templates/user_image/index_location.html
{% extends 'user_image/index.html' %}

{% block inline_css %}
{{ block.super }}
<style type="text/css">
.search_item {margin-right: 25px;}
</style>
{% endblock %}

{% block title %}
{{ block.super }}
{% with form=location_search_form %}
{% if form.ra.data and form.dec.data and form.radius.data %}
    &gt; Location: center ({{ form.ra.data }}, {{ form.dec.data }}); radius {{ form.radius.data }} deg
{% endif %}
{% endwith %}
{% endblock %}

{% block search_settings %}
<span class="search_item">RA, Dec: ({{ location_search_form.ra }}, {{ location_search_form.dec }}) degrees</span>
<span class="search_item">Radius: {{ location_search_form.radius }} degrees</span>
<input type="submit" value="Search" />
{% endblock %}

net/templates/user_image/index_recent.html
{% extends 'user_image/index.html' %}

{% block title %}
{{block.super}} &gt; 
<a href="{% url 'index_recent' %}">Recent</a>
{% endblock %}

{% block user_image_index_content %}
    {% include 'user_image/paginated_image_set.html' with image_page=image_page %}
{% endblock %}

net/templates/user_image/index_tag.html
{% extends 'user_image/index.html' %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
$(document).ready(function() {
    $("#id_query").autocomplete('/tags/autocomplete');
});
</script>
{% endblock %}

{% block title %}
{{ block.super }}
{% with form=tag_search_form %}
{% if tag %}
    &gt; Tagged with {{ tag.text }}
{% else %}
    {% if form.query.data %}
        &gt; Tag Search: '{{ form.query.data }}'
    {% endif %}
{% endif %}
{% endwith %}
{% endblock %}

{% block search_settings %}
{{ tag_search_form.query }}
<input type="submit" value="Search" />
{{ tag_search_form.exact }}
<label for="id_exact">match exact</label>
{% endblock %}

{% block search_results %}
{{ block.super }}
{% endblock %}